name: cms_flutter
description: CMS VINA MOBILE APP
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  font_awesome_flutter: ^10.2.1
  http: ^1.1.0
  shared_preferences: ^2.0.17
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.0+1
  cookie_jar: ^4.0.8
  get: ^4.6.5

  flutter_barcode_scanner: ^2.0.0
  qr_code_scanner: ^1.0.1
  flutter_beep: ^1.0.0
  audioplayers: ^5.1.0
  ota_update: ^6.0.0
  awesome_dialog: ^3.1.0
  moment_dart: ^1.0.1
  rive: ^0.11.16
  intl: ^0.18.1
  syncfusion_flutter_core: ^23.2.7
  syncfusion_flutter_gauges: ^23.2.7
  syncfusion_flutter_charts: ^23.2.7
  syncfusion_flutter_datagrid: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/
